//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRR5AVTOsalon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chek
    {
        public int id { get; set; }
        public Nullable<int> idAvtomobilya { get; set; }
        public Nullable<int> idinformation { get; set; }
        public Nullable<int> idTovari { get; set; }
        public Nullable<int> idsotrudniki { get; set; }
    
        public virtual Avtomobili Avtomobili { get; set; }
        public virtual Info Info { get; set; }
        public virtual Satrudniki Satrudniki { get; set; }
        public virtual Tovar Tovar { get; set; }
    }
}
