//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRR5AVTOsalon
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModeliAvtomobila
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModeliAvtomobila()
        {
            this.Avtomobili = new HashSet<Avtomobili>();
        }
    
        public int id { get; set; }
        public Nullable<int> idmarki { get; set; }
        public string NazvaniyeModeli { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Avtomobili> Avtomobili { get; set; }
        public virtual MarkaAvtomobila MarkaAvtomobila { get; set; }
    }
}
